name: Course deployment
description: Deploy courses to quantargo.com

inputs:
  api-key:
    description: 'The API key of your Quantargo user'
    required: true
  course-id:
    description: 'The ID of the course you want to deploy. If you do not have an ID yet, create a new course first on https://quantargo.com/dashboard/courses'
    required: true
 
# QBITURL env

# outputs:
#   course-url:
#     description: "The URL of your course"
#     value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - name: Install packages
      shell: bash
      run: |
        sudo apt-get install libopenblas-dev libcurl4-openssl-dev libmagick++-dev
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.5'

    - uses: r-lib/actions/setup-pandoc@v1

    - uses: r-lib/actions/setup-renv@v1
      with:
        cache-version: 2
    
    - name: Install SO Files
      shell: bash
      run: |
        export R_HOME=$(Rscript -e "cat(Sys.getenv('R_HOME'))")
        echo $R_HOME
        aws --region eu-central-1 --no-sign-request s3 sync s3://quantargo-repo-public/r/bin/linux/ubuntu-20.04/contrib/4.0.5/SOFiles/ sofiles
        sudo mv sofiles/* $R_HOME/lib
        rm -rf sofiles

    - name: Install Python deployment packages
      shell: bash
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq python3-pip
        sudo pip3 install pyyaml python-frontmatter lxml pytz python-dateutil

    - name: Copy action files to repository root
      shell: bash
      run: cp ${{ github.action_path }}/* .

    - name: Install R packages next
      if: endsWith(github.ref, '/next')
      run: |
        options("repos" = list(QUANTARGO="https://repository.quantargo.com/ubuntu-20.04/r-4.0.5"))
        renv::restore()
        install.packages("remotes")
        remotes::install_github(paste(c("quantargo/qbit", "quantargo/qlearn"), "next", sep="@"), upgrade="never")
        webshot::install_phantomjs()
      shell: Rscript {0}

    - name: Install R packages master
      if: endsWith(github.ref, '/master')
      run: |
        options("repos" = list(QUANTARGO="https://repository.quantargo.com/ubuntu-20.04/r-4.0.5"))
        renv::restore()
        install.packages("remotes")
        remotes::install_github(paste(c("quantargo/qlearn"), "master", sep="@"), upgrade="never")
        webshot::install_phantomjs()
      shell: Rscript {0}

    - name: Production Deployment Content
      env:
        STAGE: prod
        QKEY: ${{ inputs.api-key }}
      if: endsWith(github.ref, '/master')
      shell: bash
      run: |
        make deploy SLUG=${{ inputs.course-id }}

    - name: Development Deployment Content
      env:
        STAGE: dev
        QKEY: ${{ inputs.api-key }}
      if: endsWith(github.ref, '/next')
      shell: bash
      run: |
        make deploy SLUG=${{ inputs.course-id }}

